### ISSUE TITLE
Errors in logs when only one replica fails

### ISSUE THREAD

**Issue by asvyazin** [vostok/clusterclient.transport.sockets#5]
Original issue: https://github.com/vostok/clusterclient.core/issues/7

[Issue](https://github.com/vostok/clusterclient.core/issues/7) in `clusterclient.core` actually happens in `clusterclient.transport.webrequest` (which is not recommended clusterclient transport in .net core AFAIK). Here is what happens if `clusterclient.transport.sockets` (recommended transport) is used in a similar situation:
```
2020-01-14 13:19:38,962 ERROR [T-27817d02] Unknown transport exception has occurred while sending request to dtl-singular30.
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at Vostok.Clusterclient.Transport.Sockets.SocketsTransport.SendAsync(Request request, Nullable`1 connectionTimeout, CancellationToken token)
```
Different exception but there is an error in logs again.

This one is logged by `Vostok.Clusterclient.Transport.Sockets.ErrorHandler.TryHandle` (here it is btw: https://github.com/vostok/clusterclient.transport.sockets/blob/d4dea96ff8c0a953ccf1eb59879d27ee0cfa5bcd/Vostok.ClusterClient.Transport.Sockets/ErrorHandler.cs#L23). I puzzled about this error for some time because there is code in the beginning of `TryHandle` which checks if cancellation token is cancelled and it should be cancelled if exception is `TaskCancelledException`, right? Not really... I believe that reason for this situation is this code: https://github.com/dotnet/runtime/blob/dc0c4e975676b61ef66c7a077cc317c28764329d/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L610 .Net runtime creates another (linked) cancellation token if there is connectTimeout in http request settings and cancels it (after specified timeout), but original token remains not cancelled.

To fix it `TryHandle` should probably check `TaskCancelledException` explicitly *in addition to `token.IsCancellationRequested`* or do not set `connectTimeout` at all and handle timeouts all by itself. Both "solutions" look slightly counterintuitively to me but I can file a PR if there are no better ideas.

**Comment by iloktionov** [comment]
Fixed in https://github.com/vostok/clusterclient.transport.sockets/commit/e6ef2416c80ef73df24a0e44fd124f9aeb025ebc
